### ISSUE TITLE
Make sure the tests pass on Windows

### ISSUE THREAD

**Issue by Mackiovello** [Starcounter/Starcounter.Nova.Cli#25]
I\m not confident that all the tests will work on Windows. So I have to check that and possibly fix the stuff that doesn't work

**Comment by Mackiovello** [comment]
All the unit tests pass and a couple of the integration tests. Some of them fail though:

```
Test run for C:\Users\Star\Desktop\Starcounter.Nova.Cli\test\Starcounter.Nova.Administration.Integration\bin\Debug\netcoreapp2.1\Starcounter.Nova.Administration.Integration.dll(.NETCoreApp,Version=v2.1)
Microsoft (R) Test Execution Command Line Tool Version 15.7.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
[xUnit.net 00:00:00.5038507]     Starcounter.Nova.Administration.Integration.DbDeleteCommandTests.DeleteNonDatabaseDirectoryWithoutForce_ThrowsInvalidOperationException [FAIL]
[xUnit.net 00:00:00.5159227]     Starcounter.Nova.Administration.Integration.DbDeleteCommandTests.DeletesValidDatabaseDirectoriesWithoutForce [FAIL]
[xUnit.net 00:00:00.5460602]     Starcounter.Nova.Administration.Integration.ConfigurationTests.RetrievesConfigurationFromPreviouslyCreatedDatabase [FAIL]
[xUnit.net 00:00:00.5794480]     Starcounter.Nova.Administration.Integration.ConfigurationTests.RetrievesConfigurationFromNewlyCreatedDatabase [FAIL]
[xUnit.net 00:00:00.5821340]     Starcounter.Nova.Administration.Integration.DbCreateCommandTests.CreateDatabase_WithValidOptions_DoesntThrowAndCreatesDatabase [FAIL]
[xUnit.net 00:00:00.6141714]     Starcounter.Nova.Administration.Integration.DbCreateCommandTests.CreateDatabase_AtExistingDirectory_AddsCfgToDirectory [FAIL]
Failed   Starcounter.Nova.Administration.Integration.DbDeleteCommandTests.DeleteNonDatabaseDirectoryWithoutForce_ThrowsInvalidOperationException
Error Message:
 System.IO.IOException : The process cannot access the file 'nope.txt' because it is being used by another process.
Stack Trace:
   at System.IO.FileSystem.RemoveDirectoryRecursive(String fullPath, WIN32_FIND_DATA& findData, Boolean topLevel)
   at System.IO.FileSystem.RemoveDirectory(String fullPath, Boolean recursive)
   at System.IO.Directory.Delete(String path, Boolean recursive)
   at Starcounter.Nova.Administration.Integration.DbDeleteCommandTests.DeleteNonDatabaseDirectoryWithoutForce_ThrowsInvalidOperationException() in C:\Users\Star\Desktop\Starcounter.Nova.Cli\test\Starcounter.Nova.Administration.Integration\DbDeleteCommandTests.cs:line 60
Failed   Starcounter.Nova.Administration.Integration.DbDeleteCommandTests.DeletesValidDatabaseDirectoriesWithoutForce
Error Message:
 System.IO.IOException : The process cannot access the file 'MyDatabase.000000000000.log' because it is being used by another process.
Stack Trace:
   at System.IO.FileSystem.RemoveDirectoryRecursive(String fullPath, WIN32_FIND_DATA& findData, Boolean topLevel)
   at System.IO.FileSystem.RemoveDirectory(String fullPath, Boolean recursive)
   at System.IO.Directory.Delete(String path, Boolean recursive)
   at Starcounter.Nova.Administration.Integration.DbDeleteCommandTests.DeletesValidDatabaseDirectoriesWithoutForce() in C:\Users\Star\Desktop\Starcounter.Nova.Cli\test\Starcounter.Nova.Administration.Integration\DbDeleteCommandTests.cs:line 36
Failed   Starcounter.Nova.Administration.Integration.ConfigurationTests.RetrievesConfigurationFromPreviouslyCreatedDatabase
Error Message:
 System.Exception : Unable to start the database
Stack Trace:
   at Starcounter.Nova.Administration.ScCreateDbWrapper.Create(IDbInitializationOptions options) in C:\Users\Star\Desktop\Starcounter.Nova.Cli\src\Starcounter.Nova.Administration\Database\ScCreateDbWrapper.cs:line 24
   at Starcounter.Nova.Administration.Database.Create(IDbInitializationOptions options) in C:\Users\Star\Desktop\Starcounter.Nova.Cli\src\Starcounter.Nova.Administration\Database\Database.cs:line 36
   at Starcounter.Nova.Administration.Integration.ConfigurationTests.RetrievesConfigurationFromPreviouslyCreatedDatabase() in C:\Users\Star\Desktop\Starcounter.Nova.Cli\test\Starcounter.Nova.Administration.Integration\ConfigurationTests.cs:line 75
Failed   Starcounter.Nova.Administration.Integration.ConfigurationTests.RetrievesConfigurationFromNewlyCreatedDatabase
Error Message:
 System.Exception : Unable to start the database
Stack Trace:
   at Starcounter.Nova.Administration.ScCreateDbWrapper.Create(IDbInitializationOptions options) in C:\Users\Star\Desktop\Starcounter.Nova.Cli\src\Starcounter.Nova.Administration\Database\ScCreateDbWrapper.cs:line 24
   at Starcounter.Nova.Administration.Database.Create(IDbInitializationOptions options) in C:\Users\Star\Desktop\Starcounter.Nova.Cli\src\Starcounter.Nova.Administration\Database\Database.cs:line 36
   at Starcounter.Nova.Administration.Integration.ConfigurationTests.RetrievesConfigurationFromNewlyCreatedDatabase() in C:\Users\Star\Desktop\Starcounter.Nova.Cli\test\Starcounter.Nova.Administration.Integration\ConfigurationTests.cs:line 37
Failed   Starcounter.Nova.Administration.Integration.DbCreateCommandTests.CreateDatabase_WithValidOptions_DoesntThrowAndCreatesDatabase
Error Message:
 System.Exception : Unable to start the database
Stack Trace:
   at Starcounter.Nova.Administration.ScCreateDbWrapper.Create(IDbInitializationOptions options) in C:\Users\Star\Desktop\Starcounter.Nova.Cli\src\Starcounter.Nova.Administration\Database\ScCreateDbWrapper.cs:line 24
   at Starcounter.Nova.Administration.Database.Create(IDbInitializationOptions options) in C:\Users\Star\Desktop\Starcounter.Nova.Cli\src\Starcounter.Nova.Administration\Database\Database.cs:line 36
   at Starcounter.Nova.Administration.Integration.DbCreateCommandTests.CreateDatabase_WithValidOptions_DoesntThrowAndCreatesDatabase() in C:\Users\Star\Desktop\Starcounter.Nova.Cli\test\Starcounter.Nova.Administration.Integration\DbCreateCommandTests.cs:line 69
Failed   Starcounter.Nova.Administration.Integration.DbCreateCommandTests.CreateDatabase_AtExistingDirectory_AddsCfgToDirectory
Error Message:
 System.IO.IOException : The process cannot access the file 'samplefile.txt' because it is being used by another process.
Stack Trace:
   at System.IO.FileSystem.RemoveDirectoryRecursive(String fullPath, WIN32_FIND_DATA& findData, Boolean topLevel)
   at System.IO.FileSystem.RemoveDirectory(String fullPath, Boolean recursive)
   at System.IO.Directory.Delete(String path, Boolean recursive)
   at Starcounter.Nova.Administration.Integration.DbCreateCommandTests.CreateDatabase_AtExistingDirectory_AddsCfgToDirectory() in C:\Users\Star\Desktop\Starcounter.Nova.Cli\test\Starcounter.Nova.Administration.Integration\DbCreateCommandTests.cs:line 47

Total tests: 9. Passed: 3. Failed: 6. Skipped: 0.
Test Run Failed.
```

**Comment by Mackiovello** [comment]
Fixed with https://github.com/Starcounter/Starcounter.Nova.Cli/commit/1269d3171b4af5ce4ccb699908015e51b2d989d7
