### ISSUE TITLE
Unable to query database of application with different Nova version

### ISSUE THREAD

**Issue by Mackiovello** [Starcounter/Starcounter.Nova.Cli#39]
To reproduce, change the version in the [test project](https://github.com/Starcounter/Starcounter.Nova.Cli/blob/develop/test/TestProjects/CreateDatabaseTestProject/CreateDatabaseTestProject.csproj#L14) to different than the version in [Administration](https://github.com/Starcounter/Starcounter.Nova.Cli/blob/develop/src/Starcounter.Nova.Administration/Starcounter.Nova.Administration.csproj#L11).

The error;

```
[xUnit.net 00:00:02.6452209]     Starcounter.Nova.Administration.Integration.SqlCommandTests.CanQueryDatabase [FAIL]
Failed   Starcounter.Nova.Administration.Integration.SqlCommandTests.CanQueryDatabase
Error Message:
 System.AggregateException : One or more errors occurred. (Could not load file or assembly 'Starcounter.Nova, Version=0.9.9.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
) (The following constructor parameters did not have matching fixture data: AppHostFixture fixture)
---- System.IO.FileNotFoundException : Could not load file or assembly 'Starcounter.Nova, Version=0.9.9.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

---- The following constructor parameters did not have matching fixture data: AppHostFixture fixture
Stack Trace:

----- Inner Stack Trace #1 (System.IO.FileNotFoundException) -----
   at System.ModuleHandle.ResolveType(RuntimeModule module, Int32 typeToken, IntPtr* typeInstArgs, Int32 typeInstCount, IntPtr* methodInstArgs, Int32 methodInstCount, ObjectHandleOnStack type)
   at System.ModuleHandle.ResolveTypeHandleInternal(RuntimeModule module, Int32 typeToken, RuntimeTypeHandle[] typeInstantiationContext, RuntimeTypeHandle[] methodInstantiationContext)
   at System.Reflection.RuntimeModule.ResolveType(Int32 metadataToken, Type[] genericTypeArguments, Type[] genericMethodArguments)
   at System.Reflection.CustomAttribute.FilterCustomAttributeRecord(CustomAttributeRecord caRecord, MetadataImport scope, Assembly& lastAptcaOkAssembly, RuntimeModule decoratedModule, MetadataToken decoratedToken, RuntimeType attributeFilterType, Boolean mustBeInheritable, Object[] attributes, IList derivedAttributes, RuntimeType& attributeType, IRuntimeMethodInfo& ctor, Boolean& ctorHasParameters, Boolean& isVarArg)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeModule decoratedModule, Int32 decoratedMetadataToken, Int32 pcaCount, RuntimeType attributeFilterType, Boolean mustBeInheritable, IList derivedAttributes)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeType type, RuntimeType caType, Boolean inherit)
   at System.Attribute.GetCustomAttributes(MemberInfo element, Boolean inherit)
   at Starcounter.Nova.Binding.DefaultTypeSelector.<>c.<Create>b__0_0(Type type)
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at Starcounter.Nova.Binding.ClassBinder.<>c__DisplayClass0_0.<BindAllDatabaseClasses>b__0()
   at Starcounter.Nova.Database.Context.Run(Transaction txn, Action action)
   at Starcounter.Nova.Database.Context.Transact(Action action, TransactOptions options)
   at Starcounter.Nova.Database.TransactImpl.Transact(Action action, TransactOptions options)
   at Starcounter.Nova.Binding.ClassBinder.BindAllDatabaseClasses(IEnumerable`1 types)
   at Starcounter.Nova.Hosting.DefaultAppHost.InitializeHost()
   at Starcounter.Nova.Hosting.Connection.Start()
   at Starcounter.Nova.Hosting.DefaultAppHost.Start()
   at Starcounter.Nova.Administration.Integration.AppHostFixture..ctor() in /home/erlend/Starcounter/Starcounter.Nova.Cli/test/Starcounter.Nova.Administration.Integration/SqlCommandTests.cs:line 49
----- Inner Stack Trace #2 (Xunit.Sdk.TestClassException) -----

```

**Comment by Mackiovello** [comment]
This is probably related to #40

**Comment by Mackiovello** [comment]
This is because of a limitation in Nova. I've opened an internal issue (469). Closing
