### ISSUE TITLE
Classes with properties referencing other database classes are not resolved properly

### ISSUE THREAD

**Issue by Mackiovello** [Starcounter/Starcounter.Nova.Cli#51]
Part of #21 

```
$ dotnet run -- query "SELECT p FROM Person p" /home/erlend/Desktop/Reprod/MyDatabase/
Unable to execute the command: Specified argument was out of the range of valid values.
Parameter name: There's no type with the name Reprod.Pet
   at Starcounter.Nova.DatabaseReader.TypeStringParser.FindType(String typeString) in /home/erlend/Starcounter/Starcounter.Nova.Cli/src/Starcounter.Nova.DatabaseReader/TypeStringParser.cs:line 25
   at Starcounter.Nova.DatabaseReader.GeneratableGenerator.<>c__DisplayClass9_0.<GenerateProperties>b__0(Column c) in /home/erlend/Starcounter/Starcounter.Nova.Cli/src/Starcounter.Nova.DatabaseReader/GeneratableGenerator.cs:line 111
   at System.Linq.Enumerable.SelectListIterator`2.MoveNext()
   at Starcounter.Nova.Binding.PropertyEmitter.Emit()
   at Starcounter.Nova.Binding.InheritableClassBuilder.Build()
   at Starcounter.Nova.DatabaseReader.GeneratableGenerator.SetParentsAndTypesInTree(Tree`1 tree) in /home/erlend/Starcounter/Starcounter.Nova.Cli/src/Starcounter.Nova.DatabaseReader/GeneratableGenerator.cs:line 83
   at Starcounter.Nova.DatabaseReader.GeneratableGenerator.SetParentsAndTypesInTree(Tree`1 tree) in /home/erlend/Starcounter/Starcounter.Nova.Cli/src/Starcounter.Nova.DatabaseReader/GeneratableGenerator.cs:line 95
   at Starcounter.Nova.DatabaseReader.GeneratableGenerator.AddParentsAndTypes(IEnumerable`1 generatablesWithInheritenceInfo) in /home/erlend/Starcounter/Starcounter.Nova.Cli/src/Starcounter.Nova.DatabaseReader/GeneratableGenerator.cs:line 70
   at Starcounter.Nova.DatabaseReader.GeneratableGenerator.Generate() in /home/erlend/Starcounter/Starcounter.Nova.Cli/src/Starcounter.Nova.DatabaseReader/GeneratableGenerator.cs:line 30
   at Starcounter.Nova.Administration.GeneratedTypeLoader..ctor() in /home/erlend/Starcounter/Starcounter.Nova.Cli/src/Starcounter.Nova.Administration/Sql/GeneratedTypeLoader.cs:line 21
   at Starcounter.Nova.Administration.DatabaseBinder..ctor(IDatabaseClassBinder binder, ITypeLoader typeLoader) in /home/erlend/Starcounter/Starcounter.Nova.Cli/src/Starcounter.Nova.Administration/Sql/DatabaseBinder.cs:line 19
   at Starcounter.Nova.Administration.HostedQueryExecuter.Execute(String query) in /home/erlend/Starcounter/Starcounter.Nova.Cli/src/Starcounter.Nova.Administration/Sql/HostedQueryExecuter.cs:line 25
   at Starcounter.Nova.Administration.Query.Call(String query) in /home/erlend/Starcounter/Starcounter.Nova.Cli/src/Starcounter.Nova.Administration/Sql/Query.cs:line 34
   at Starcounter.Nova.Cli.QueryCommand.<>c__DisplayClass6_0.<ConstructCliApp>b__0() in /home/erlend/Starcounter/Starcounter.Nova.Cli/src/Starcounter.Nova.Cli/QueryCommand.cs:line 41
```

```cs
[Database]
public class Person
{
    public virtual Pet Pet { get; set; }
}

[Database]
public class Pet
{
    public virtual long NumberOflegs { get; set; }
}
```

I think the solution is to first generate the types as partial classes and then generate the properties. I don't see any other way right now to resolve the issue with circular references.

**Comment by Mackiovello** [comment]
Looking more into this, it doesn't seem to be possible to generate partial classes. Partial classes are combined at compile time, so it doesn't make sense to generate them in run time.

I'm looking at using abstract classes instead:
1. In the first pass, just generate abstract classes with no properties
2. in the second pass create an implementation of those classes and let the properties refer to the abstract classes

This means that all the types exist after the first pass which means that we can reference them.

@linkdata does this make sense? 

What I'm not sure about is what the output should be if your querying the property of a class that references another class. In 2.4, you'd get the ObjectNo. What should be used here?

**Comment by linkdata** [comment]
> @linkdata does this make sense?

Not sure. I think what you want is a forward reference. Not sure how C# handles those. But start with the abstract classes. If that works, all good.

> In 2.4, you'd get the ObjectNo. What should be used here?

The same. Otherwise you'll end up trying to print a possibly recursive graph on each line.

**Comment by Mackiovello** [comment]
I'm confused now. This is in my debug console:

```
Loaded 'CreateDatabaseTestProject.TestPerson_AbstractAssembly'. 
Loaded 'CreateDatabaseTestProject.InheritedPerson_AbstractAssembly'. 
Loaded 'CreateDatabaseTestProject.Pet_AbstractAssembly'. 
Loaded 'CreateDatabaseTestProject.TestPerson_Assembly'. 
Loaded 'CreateDatabaseTestProject.InheritedPerson_Assembly'. 
Loaded 'CreateDatabaseTestProject.InheritedPerson_Assembly'. 
Loaded 'CreateDatabaseTestProject.Pet_Assembly'. 
Loaded 'CreateDatabaseTestProject.TestPerson_Assembly'. 
```

This seems correct. All the abstract and the non-abstract generated classes are loaded. The problem is that I'm not able to find the types in these assemblies. 

All SO answers, for example https://stackoverflow.com/questions/866487/how-to-retrieve-info-on-a-loaded-assembly-at-runtime-c-net?rq=1, use `GetReferencedAssemblies()` or `AppDomain.CurrentDomain.GetAssemblies()`. If I use `GetReferencedAssemblies`, I don't get the dynamically generated assemblies and there's no `AppDomain` in .NET Standard. 

The weird thing that I don't understand is that it works when I don't try to use the abstract generated classes. Next step is to investigate why that is.

**Comment by Mackiovello** [comment]
> The weird thing that I don't understand is that it works when I don't try to use the abstract generated classes. Next step is to investigate why that is.

That was dumb by me. It works because I don't have any property references. I think I might be thinking about this the wrong way.

**Comment by Mackiovello** [comment]
It feels like `GetType` and `GetTypes` have different behavior which screws me over. I'll have to investigate this. `GetType` doesn't seem to only retrieve types that are defined in the assembly.

**Comment by linkdata** [comment]
Possibly relevant: https://stackoverflow.com/questions/12432998/ilgenerator-declarelocal-takes-a-type-of-a-class-not-yet-compiled

**Comment by Mackiovello** [comment]
> The primary insight you need here is that TypeBuilder derives from Type.

That's possibly a game-changer. Thanks for the link!

**Comment by Mackiovello** [comment]
> What I'm considering now is that instead of trying to set the type of the properties that reference other tables, we just set the type to something that can identify the actual type and then use reflection to find the ObjectNo. By doing that, we never need the type before it's loaded. I'm not 100% that it'll work, but it's the only option I see right now.

With that logic, it would make sense to set it to `IDbProxy` and then call `DbGetIdentity` when querying. Let's try that.

**Comment by Mackiovello** [comment]
Okay, this seems to work. Finally. Making final cleanup for PR's and then moving on from this.

**Comment by Mackiovello** [comment]
Yes, I tried doing it in two passes. The reason it didn't work is because I tried to use reflection to find the types for the properties and the database classes weren't loaded soon enough for that to work. If I'd instead used reflection for all types, except for database classes, it probably would work. That would be a more complex solution though.

Since we set the property type for properties referencing database classes to `IDbProxy`, we can still use reflection to find the actual type. Although, there's no need for that since we only need the ID.

Also, is there a difference between `ObjectNo` in level1 and the result from `DbGetIdentity` of `IDbProxy`?

**Comment by linkdata** [comment]
> Although, there's no need for that since we only need the ID.

I was thinking about use cases other than the CLI needs (like the migrator @miyconst wrote, maybe?). For the CLI this should be fine. We can revisit it later if the need arises.

> Also, is there a difference between ObjectNo in level1 and the result from DbGetIdentity of IDbProxy?

No, those are the same value.

**Comment by miyconst** [comment]
>I was thinking about use cases other than the CLI needs (like the migrator @miyconst wrote, maybe?). For the CLI this should be fine. We can revisit it later if the need arises.

Sorry, I am a bit out of the conversation, what is that might be needed for the Migrator?

**Comment by Mackiovello** [comment]
> Sorry, I am a bit out of the conversation, what is that might be needed for the Migrator?

I don't think this is applicable for the Migrator since the migrator writes source code instead of generating types, so it doesn't have the same problem.

**Comment by miyconst** [comment]
Just to clarify:

- @Mackiovello meant [`Starcounter.DbConverter`](https://github.com/Starcounter/Starcounter.DbConverter) not [`Starcounter.Migrator`](https://github.com/Starcounter/Starcounter.Migrator).
- The `DbConverter` generates source code files for the later usage, it does not even compile it. The goal is to get the source files, thus current issue is not relevant.

**Comment by linkdata** [comment]
Ok, good to know.

**Comment by Mackiovello** [comment]
This was fixed with https://github.com/Starcounter/Starcounter.Nova.Cli/pull/58
