### ISSUE TITLE
ScErrTypeNotFound with certain WHERE clauses

### ISSUE THREAD

**Issue by Mackiovello** [Starcounter/Starcounter.Nova.Cli#79]
```
$ dotnet run -- query "SELECT p FROM Reprod.Pet p" ~/Desktop/Reprod/MyDatabase/

| ID | NumberOflegs | Owner |
|----|--------------|-------|
| 2  | 4            | 1     |
| 4  | 4            | 3     |

$ dotnet run -- query "SELECT p FROM Reprod.Pet p WHERE p.NumberOfLegs = '4'" ~/Desktop/Reprod/MyDatabase/
Unable to execute the command: ScErrTypeNotFound (SCERR15003): There is no type in the database for the given type name.
   at Starcounter.Nova.Query.QueryEnumerator`1.System.Collections.IEnumerator.MoveNext()
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at Starcounter.Nova.Administration.MarkdownPrintableTableFactory.Create() in /home/erlend/Starcounter/Starcounter.Nova.Cli/src/Starcounter.Nova.Administration/Sql/MarkdownPrintableTableFactory.cs:line 23
   at Starcounter.Nova.Administration.CommandLineSqlResult..ctor(IEnumerable`1 items, IPrintableTableFactory printableTableFactory) in /home/erlend/Starcounter/Starcounter.Nova.Cli/src/Starcounter.Nova.Administration/Sql/CommandLineSqlResult.cs:line 19
   at Starcounter.Nova.Administration.HostedQueryExecuter.<>c__DisplayClass2_0.<Execute>b__0() in /home/erlend/Starcounter/Starcounter.Nova.Cli/src/Starcounter.Nova.Administration/Sql/HostedQueryExecuter.cs:line 30
   at Starcounter.Nova.Database.Context.Run[T](Transaction txn, Func`1 fn)
   at Starcounter.Nova.Database.Context.Transact[T](Func`1 function, TransactOptions options)
   at Starcounter.Nova.Database.TransactImpl.Transact[T](Func`1 function, TransactOptions options)
   at Starcounter.Nova.Administration.HostedQueryExecuter.Execute(String query) in /home/erlend/Starcounter/Starcounter.Nova.Cli/src/Starcounter.Nova.Administration/Sql/HostedQueryExecuter.cs:line 28
   at Starcounter.Nova.Administration.Query.Call(String query) in /home/erlend/Starcounter/Starcounter.Nova.Cli/src/Starcounter.Nova.Administration/Sql/Query.cs:line 34
   at Starcounter.Nova.Cli.QueryCommand.<>c__DisplayClass6_0.<ConstructCliApp>b__1() in /home/erlend/Starcounter/Starcounter.Nova.Cli/src/Starcounter.Nova.Cli/QueryCommand.cs:line 46
````

In other queries, it works just fine:

```
$ dotnet run -- query "SELECT p FROM Starcounter.Metadata.RawView p WHERE p.FullName = 'Individual'" ~/Desktop/Reprod/MyDatabase/

| ID                   | LayoutHandle | Inherits             | Updatable | FullName   | UniqueIdentifierReversed   | UniqueIdentifier           | Name       |
|----------------------|--------------|----------------------|-----------|------------|----------------------------|----------------------------|------------|
| 18446744073709551086 | 33           | 18446744073709551553 | True      | Individual | Individual.Raw.Starcounter | Starcounter.Raw.Individual | Individual |
```

This is confusing. We're using the new QP, so it's probably related to how it works.

**Comment by Mackiovello** [comment]
I clearly don't understand how this works:

```
$ dotnet run -- query "SELECT r FROM Pet r" ~/Desktop/Reprod/MyDatabase/
| ID | NumberOflegs | Owner |
|----|--------------|-------|
| 2  | 4            | 1     |
| 4  | 4            | 3     |

$ dotnet run -- query "SELECT r FROM Pet r WHERE r.Owner = 3" ~/Desktop/Reprod/MyDatabase/
| ID | AngerLevel | NumberOflegs | Owner |
|----|------------|--------------|-------|
| 4  | 42         | 4            | 3     |
```

**Comment by Mackiovello** [comment]
The actual problem is with error reporting. Closing in favor of https://github.com/Starcounter/level0/issues/1197
